install:
  - curl https://www.apache.org/dyn/closer.cgi?path=/kafka/0.8.1/kafka_2.9.2-0.8.1.tgz > kafka.tgz
  - tar -xzf kafka.tgz
  - cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &
language: java
before_script:
  - npm install -g nodeunit
  - npm install --dev
script: nodeunit tests
